version: "2"

plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    exclude_patterns:
      - '**/tests/**'
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - '**/tests/**'

exclude_patterns: []
