version: "2"

plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
    checks:
      E701:
        # Allow multiple statements on one line (colon) because that's how type
        # annotations are written. If Codeclimate ever updates their tool to
        # support that notation then we should re-enable that check.
        enabled: false
  radon:
    enabled: true
    exclude_patterns:
      - '**/tests/**'
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - '**/tests/**'

exclude_patterns: []
