sudo: false
language: python
python:
  - "3.6"
  - "3.7-dev"
  - "pypy3"
# Taken from https://github.com/oz123/pytest-localftpserver
matrix:
  include:
    - os: osx
      language: generic
      python: 3.6
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - pip install tox
        - conda install -y --name py36 virtualenv
      script: tox -e py36,lint,lint-not-windows,test,security
install: pip install codecov tox-travis
env:
  - TOX_SKIP_MISSING_INTERPRETERS=False
script: tox
after_success:
  - codecov
notifications:
  slack:
    secure: aV2yV0GJrWzF2F6FPVG7WiKWkjYClBzWxr4BrojnBR8zj2CJ/MMMpZvAbma3KQkJx7cYGlr0XbCJ6vEnSfcVachyHlEbjWM95yQVxBhtfvmh8gldkSMyv950gqruNRb5uNkoKOfm6iY3vooHjWOOBLML9Xhb3E3T0qPQpgk7PSvCeZtkz5sWurGK+dalvCZBLmBkSSqJfXHDdOYpyPbg+WBLR8jkpmjVW1sVKFCTrNQooJUJQKrV//Xb4I/GDkL25078L2RptRrY/RLW/pewf9omg67NZ71mUqCCmnbbWTImYvJSEHSWumq31tRPUKWzZ9WV0Ors2HDpc2BcdJLl1qfLFkCUxcQzmRYYr3rlg4Mn4m6Jm5XN2nNE7ffiD42brINw/00lhzQuhnORcX8OP7eTa3EfFFopbbcE9PGclW4/saL3TtOz6A3ov613Ig/fVyfbPGy8Sx2PVlpIGIW0lHgw3gzqNTFuYqX1pnvgaE67xNhI8IznMdd9xM4hSwAV81I5Yzi6Bd6qEYYmDUfcOBGbeb1tJWsC/E57DxJL97/7dfkwWy/0E3qywY2+iS08RY0Y+oKStg8eC0eCO/Cqq1LnQgrYgLJEhxFBKo1kyL1g+Tv1+BGLe94HlnGbMBP886LTRVmiCjqvkn/k2B+PnMNuZvcWw/WUv64FtUGpw+o=
