build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

init: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  - pip install -U tox

test_script: tox
